name: watt_hub
description: "A new Flutter project."
publish_to: "none"

version: 3.24.3

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  watt_hub_localization:
    path: packages/watt_hub_localization
  watt_hub_uikit:
    path: packages/watt_hub_uikit
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  injectable: ^2.4.4
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  auto_route: ^9.2.2
  get_it: 7.7.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

