name: watt_hub
description: "A new Flutter project."
publish_to: "none"

version: 3.24.3

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  watt_hub_localization:
    path: packages/watt_hub_localization
  watt_hub_uikit:
    path: packages/watt_hub_uikit
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  injectable: ^2.4.4
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  auto_route: ^9.2.2
  get_it: 7.7.0
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  url_launcher: ^6.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  flutter_rating_bar: ^4.0.1
  flutter_map_marker_cluster: ^1.4.0
  retrofit: ^4.4.1
  flutter_secure_storage: ^9.2.2
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  retrofit_generator: ^9.1.3

flutter:
  uses-material-design: true
