name: watt_hub_uikit
description: "A new Flutter package project."
version: 0.0.1
# homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  awesome_extensions: ^2.0.17

  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8
  pinput: ^5.0.0
  dropdown_button2: ^2.3.9
  smooth_page_indicator: ^1.2.0+3
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  intl: ^0.19.0

  image_picker: ^1.1.2
  permission_handler: ^10.2.0
  image_picker_android:
  image_picker_platform_interface:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen: ^5.7.0
  flutter_gen_runner: ^5.7.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/src/assets
  line_length: 100

  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      class_name: WattHubAssets

  integrations:
    flutter_svg: true
